# Generated by Django 5.0.6 on 2024-07-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'verbose_name': 'Planet', 'verbose_name_plural': 'Planets'},
        ),
    ]
